// ABOUTME: Sidebar configuration for The AI Field Guide
// ABOUTME: Auto-generates from docs folder structure; override per-topic as needed
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  fieldGuideSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
